name: ci
on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version' # Read python version from a file

      - name: Set up poetry
        uses: Gr1N/setup-poetry@v9

      - name: Runs tests and static analysis
        shell: bash
        run: make test
